# Generated by Django 6.0.3 on 2026-03-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('broker_name', models.CharField(max_length=255)),
                ('broker_email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'broker',
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('society_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('society_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'society',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.society')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='BrokerSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.broker')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.society')),
            ],
            options={
                'db_table': 'broker_society',
            },
        ),
    ]
